name = "spinmachocasino-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmachocasino.gr"
HMAC_KEY = "5b4cad5fdb837a5eaf6b5bba924afc44a18f4355c5c26ff03cca1cd6217911fa"
COOKIE_NAME = "56z"
PLAY_PATH = "start-now"
BUTTON_ID = "p500de6020f32d120d5838b9aa879970a"
GATE_SALT = "94f15df48b0cc759"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "xw2x"
CTA_SELECTOR = ".play-button"
